/**
 * Byteville Defenders: class server (Google Apps Script).  Version 2 (secured).
 *
 * This file is generated by "npm run build". Paste the whole file into Apps Script.
 *
 * What it does
 *   - Saves every student answer as a row in the "events" tab.
 *   - Checks answers itself. The "verified" column is the server's decision, not the browser's.
 *   - Night Watch: checks solutions, hands out passcodes, and scores levels. The game itself
 *     does not contain the Night Watch answers or passcodes.
 *   - Leaderboard: built only from verified results.
 *   - Rate limits: slows down guessing and spam.
 *
 * This file holds NO secrets and is the same for every school. Your Night Watch answers and
 * passcodes come from YOUR secret seed, stored in Project Settings > Script properties as NW_SEED.
 * It must match the NW_SEED used to build your website. See the Teacher Kit for setup.
 */

// Optional shared key. If you set it here, set the same value as classKey in js/config.js.
const CLASS_KEY = '';

const SHEET_NAME = 'events';
const COLUMNS = ['received_at', 'timestamp', 'session_id', 'student', 'class_code', 'event', 'chapter', 'item_id',
  'prompt', 'choice', 'correct_answer', 'correct', 'time_ms', 'points', 'total_points', 'verified'];
const CLIENT_EVENTS = ['start', 'lesson', 'check', 'answer', 'chapter_complete', 'finish'];

/* ---------------- school secret ---------------- */
function seed_() { return PropertiesService.getScriptProperties().getProperty('NW_SEED') || ''; }

const ADJ = ['amber','ashen','autumn','bold','brisk','calm','cedar','cobalt','copper','coral','crimson','dawn','dusk','ember','fern','frost',
  'gentle','golden','granite','hollow','indigo','ivory','jade','lunar','maple','misty','noble','north','ocean','olive','opal','pine',
  'quiet','rapid','river','ruby','rustic','saffron','sage','scarlet','shadow','silver','slate','solar','spruce','stone','storm','sunny',
  'swift','tidal','timber','topaz','twilight','velvet','violet','wild','willow','winter','wise','young','zephyr','iron','hazel','birch'];
const NOUN = ['anchor','anvil','atlas','beacon','bridge','canyon','castle','cipher','comet','compass','crane','delta','falcon','feather','fjord','forge',
  'garden','glacier','harbor','hawk','heron','island','keep','kernel','lantern','ledger','lyric','meadow','meridian','mesa','orbit','orchid',
  'otter','pebble','pilot','prism','quarry','quilt','raven','reef','ridge','rocket','sail','signal','sparrow','spire','summit','thicket',
  'tiger','torch','tower','trail','valley','vault','voyage','warden','wave','whisper','wolf','wren','yarrow','zenith','harp','oasis'];

/** Passcode for a solved level: HMAC-SHA256 of the level with your secret seed, turned into words. */
function passcode_(levelId) {
  const sig = Utilities.computeHmacSha256Signature('passcode:' + levelId, seed_());
  const b = sig.map(function (x) { return x & 255; });
  return ADJ[b[0] % 64] + '-' + NOUN[b[1] % 64] + '-' + (10 + (b[2] % 90));
}
function levelForPasscode_(code, track) {
  const c = String(code || '').trim().toLowerCase();
  const ids = track === 'op' ? BV.OP_IDS : BV.NW_IDS;
  for (let i = 0; i < ids.length; i++) if (passcode_(ids[i]) === c) return i + 1;
  return 0;
}

/** Teacher helper: Run this in the Apps Script editor to print YOUR answer key in the Execution log. */
function showNightWatchAnswers() {
  if (!seed_()) { Logger.log('Set NW_SEED first: Project Settings > Script properties.'); return; }
  const a = BV.logAnswers(seed_());
  Logger.log('Log-hunt answers: level 3 = ' + a.nw3 + ', level 4 = ' + a.nw4 + ', level 7 = ' + a.nw7 + ', level 11 = ' + a.nw11);
  BV.NW_IDS.forEach(function (id, i) { Logger.log('Night Watch passcode after level ' + (i + 1) + ': ' + passcode_(id)); });
  const o = BV.opAnswers(seed_());
  Logger.log('Control Room answers: 1 = ' + o.op1 + ', 2 = ' + o.op2 + ', 3 = ' + o.op3 + ', 4 = ' + o.op4 + ', 5 = ' + o.op5 + ', 6 = ' + o.op6 + ', 9 = ' + o.op9 + ', 10 block = ' + o.op10);
  BV.OP_IDS.forEach(function (id, i) { Logger.log('Control Room password after level ' + (i + 1) + ': ' + passcode_(id)); });
  Logger.log('Rule-writing levels have no single answer. See the Teacher Kit for sample solutions.');
}

function setup() {
  if (!seed_()) Logger.log('Reminder: add your secret NW_SEED in Project Settings > Script properties to turn on Night Watch.');
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  let sh = ss.getSheetByName(SHEET_NAME);
  if (!sh) sh = ss.insertSheet(SHEET_NAME);
  if (sh.getLastRow() === 0) sh.appendRow(COLUMNS);
  // Upgrade an older sheet: make sure every header is present.
  sh.getRange(1, 1, 1, COLUMNS.length).setValues([COLUMNS]).setFontWeight('bold');
  sh.setFrozenRows(1);
  return sh;
}

function sheet_() {
  const sh = SpreadsheetApp.getActiveSpreadsheet().getSheetByName(SHEET_NAME);
  if (!sh || sh.getLastColumn() < COLUMNS.length) return setup();
  return sh;
}

/** Plain text only. Stops spreadsheet formula injection (= + - @) and control characters. */
function clean_(v, max) {
  let s = v === null || v === undefined ? '' : String(v);
  s = s.replace(/[\u0000-\u0008\u000B-\u001F\u007F]/g, ' ').slice(0, max || 300);
  if (/^[=+\-@\t\r]/.test(s)) s = "'" + s;
  return s;
}
function num_(v, lo, hi) {
  const n = Number(v);
  if (v === '' || v === null || v === undefined || !isFinite(n)) return '';
  return Math.max(lo, Math.min(hi, Math.round(n)));
}
function name_(v) { return clean_(String(v || '').trim(), 40); }
function cls_(v) { return clean_(String(v || '').trim().toUpperCase(), 30); }

/** Simple rate limiter. Returns true when the caller is over the limit. */
function limited_(key, max, seconds) {
  const cache = CacheService.getScriptCache();
  const n = Number(cache.get(key) || 0) + 1;
  cache.put(key, String(n), seconds);
  return n > max;
}

function doPost(e) {
  let body;
  try {
    const raw = (e && e.postData && e.postData.contents) || '';
    if (raw.length > 60000) return json_({ error: 'too large' });
    body = JSON.parse(raw || '{}');
  } catch (err) { return json_({ error: 'bad request' }); }
  if (CLASS_KEY && body.key !== CLASS_KEY) return json_({ error: 'bad key' });
  if (body.action === 'nwcheck') return nwCheck_(body);
  if (body.action === 'nwpass') return nwPass_(body);
  return saveEvents_(body);
}

function saveEvents_(body) {
  const events = Array.isArray(body.events) ? body.events.slice(0, 50) : [];
  if (!events.length) return json_({ saved: 0 });
  const session = clean_(events[0].session_id, 60);
  if (limited_('ev_' + session, 400, 600)) return json_({ error: 'slow down' });
  const now = new Date().toISOString();
  const rows = [];
  events.forEach(function (ev) {
    const type = String(ev.event || '');
    if (CLIENT_EVENTS.indexOf(type) < 0) return;
    const chapter = String(ev.chapter || '');
    if (BV.VALID_CHAPTERS.indexOf(chapter) < 0) return;         // Night Watch rows come only from the server
    const item = clean_(ev.item_id, 60);
    const choice = clean_(ev.choice, 300);
    const verified = (type === 'answer' || type === 'check') ? BV.verifyItem(String(ev.item_id || ''), String(ev.choice || '')) : '';
    rows.push([now, clean_(ev.timestamp, 40), clean_(ev.session_id, 60), name_(ev.student), cls_(ev.class_code), type, chapter, item,
      clean_(ev.prompt, 300), choice, clean_(ev.correct_answer, 200), num_(ev.correct, 0, 100), num_(ev.time_ms, 0, 86400000),
      num_(ev.points, 0, 1000), num_(ev.total_points, 0, 100000), verified]);
  });
  if (!rows.length) return json_({ saved: 0 });
  write_(rows);
  return json_({ saved: rows.length });
}

function write_(rows) {
  const lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    const sh = sheet_();
    sh.getRange(sh.getLastRow() + 1, 1, rows.length, COLUMNS.length).setValues(rows);
  } finally { lock.releaseLock(); }
}

/* ---------------- Night Watch ---------------- */
function nwCheck_(b) {
  const level = BV.levelMeta(String(b.level || ''));
  const student = name_(b.student), cls = cls_(b.class_code), session = clean_(b.session_id, 60);
  if (!level || !student || !session) return json_({ error: 'bad request' });
  if (!seed_()) return json_({ error: 'Night Watch is not set up on this server yet (NW_SEED is missing).' });
  if (limited_('nw_all', 4000, 3600)) return json_({ wait: true, message: 'The class server is busy. Try again in a few minutes.' });
  // Anti-guessing: at most one check every 2 seconds per level, and 60 per level per hour.
  if (limited_('nwq_' + session + level.id, 1, 2)) return json_({ wait: true, message: 'Wait 2 seconds between checks.' });
  if (limited_('nwh_' + session + level.id, 60, 3600)) return json_({ wait: true, message: 'Too many tries on this level. Take a break and come back in an hour.' });
  const submission = String(b.submission || '').slice(0, 4000);
  const res = BV.check(level.id, submission, seed_());
  const props = PropertiesService.getScriptProperties();
  const who = (cls + '|' + student).slice(0, 60);
  const failKey = 'f|' + who + '|' + level.id, doneKey = 'd|' + who + '|' + level.id;
  const now = new Date().toISOString();
  const hints = num_(b.hints, 0, 2) || 0;
  if (!res.ok) {
    const fails = Number(props.getProperty(failKey) || 0) + 1;
    props.setProperty(failKey, String(fails));
    write_([[now, now, session, student, cls, 'nw_check', level.id.slice(0, 2), level.id, level.title, clean_(submission, 300), '', 0, '', 0, '', 0]]);
    return json_({ ok: false, failed: (res.failed || []).slice(0, 10) });
  }
  const base = level.base;
  const fails = Number(props.getProperty(failKey) || 0);
  const points = Math.max(Math.round(base * 0.25), Math.round(base * (1 - 0.25 * hints)) - 5 * fails);
  const prev = Number(props.getProperty(doneKey) || 0);
  const rows = [[now, now, session, student, cls, 'nw_check', level.id.slice(0, 2), level.id, level.title, clean_(submission, 300), '', 1, '', points, '', 1]];
  if (!prev) {
    props.setProperty(doneKey, String(points));
    rows.push([now, now, session, student, cls, 'chapter_complete', level.id, level.id + '-done', level.title,
      hints + ' hints', '', fails, '', points, '', 1]);
  }
  write_(rows);
  CacheService.getScriptCache().remove('lb_' + cls);
  return json_({ ok: true, points: prev || points, passcode: passcode_(level.id) });
}

function nwPass_(b) {
  const session = clean_(b.session_id, 60);
  if (!session || !seed_()) return json_({ level: 0, message: 'Night Watch is not set up on this server yet.' });
  // Per-player and whole-class limits, so nobody can try thousands of passcodes.
  if (limited_('nwp_' + session, 15, 3600) || limited_('nwp_all', 300, 3600)) return json_({ level: 0, message: 'Too many passcode tries. Wait an hour.' });
  return json_({ level: levelForPasscode_(b.code, b.track === 'op' ? 'op' : 'nw') });
}

/* ---------------- leaderboard (verified results only) ---------------- */
function doGet(e) {
  const p = (e && e.parameter) || {};
  if (p.action !== 'leaderboard') return ContentService.createTextOutput('Byteville server is running.');
  const cls = cls_(p['class']);
  const cache = CacheService.getScriptCache();
  const key = 'lb_' + cls;
  const hit = cache.get(key);
  if (hit) return text_json_(hit);
  const sh = sheet_();
  const by = {};
  if (sh.getLastRow() > 1) {
    const data = sh.getRange(2, 1, sh.getLastRow() - 1, COLUMNS.length).getValues();
    const I = {}; COLUMNS.forEach(function (c, i) { I[c] = i; });
    data.forEach(function (r) {
      if (String(r[I.class_code]).toUpperCase() !== cls || r[I.verified] !== 1) return;
      const name = String(r[I.student]);
      const s = by[name] || (by[name] = { student: name, items: {}, nw: {} });
      const ev = r[I.event];
      if (ev === 'answer' || ev === 'check') s.items[BV.scoreKey(String(r[I.item_id]))] = true;
      if (ev === 'chapter_complete' && /^(nw|op)\d+$/.test(String(r[I.chapter]))) s.nw[r[I.chapter]] = Number(r[I.points]) || 0;
    });
  }
  const rows = Object.keys(by).map(function (k) {
    const s = by[k];
    const nw = Object.keys(s.nw).reduce(function (a, l) { return a + s.nw[l]; }, 0);
    return { student: s.student, points: Object.keys(s.items).length * 10 + nw, chapters: Object.keys(s.nw).length };
  }).sort(function (a, b) { return b.points - a.points; }).slice(0, 10);
  const out = JSON.stringify({ rows: rows, verified: true });
  cache.put(key, out, 60);
  return text_json_(out);
}

function json_(o) { return text_json_(JSON.stringify(o)); }
function text_json_(s) { return ContentService.createTextOutput(s).setMimeType(ContentService.MimeType.JSON); }
