// Builds the game (js/app.js) and the class server (backend/Code.gs). Run with: npm run build
//
// Your school's secret seed comes from the NW_SEED environment variable (GitHub Actions secret)
// or from private/nw-seed.txt. If neither exists, a new random seed is created in private/.
// The private/ folder is ignored by git. Never commit it.
const { execSync } = require('child_process');
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname, '..');
const run = c => execSync(c, { cwd: root, stdio: 'inherit' });
const P = (...a) => path.join(root, ...a);

let seed = (process.env.NW_SEED || '').trim();
if (!seed && fs.existsSync(P('private/nw-seed.txt'))) seed = fs.readFileSync(P('private/nw-seed.txt'), 'utf8').trim();
if (!seed) {
  if (process.env.CI) { console.error('STOP: add a repository secret named NW_SEED (Settings > Secrets and variables > Actions).'); process.exit(1); }
  seed = crypto.randomBytes(24).toString('base64url');
  fs.mkdirSync(P('private'), { recursive: true });
  fs.writeFileSync(P('private/nw-seed.txt'), seed + '\n');
  console.log('Created a new secret seed in private/nw-seed.txt. Keep it private.');
}
if (seed.length < 12) { console.error('STOP: NW_SEED must be at least 12 characters.'); process.exit(1); }

// 1. Generate this school's Night Watch logs (logs only, no answers).
run('npx esbuild tools/gen-entry.ts --bundle --platform=node --format=cjs --outfile=tools/.gen.cjs --log-level=warning');
const { generateLogs, FW_HEADER, generateTerminal } = require('./.gen.cjs');
const g = generateLogs(seed);
const term = generateTerminal(seed);
fs.unlinkSync(P('tools/.gen.cjs'));
fs.writeFileSync(P('src/nightwatch/logs.generated.ts'),
  '// Generated by npm run build from your NW_SEED. Logs only: no answers. Do not edit.\n' +
  `export const FW_HEADER = ${JSON.stringify(FW_HEADER)};\nexport const LOGS: Record<string, string[]> = ${JSON.stringify(g.logs)};\n`);

fs.writeFileSync(P('src/terminal/data.generated.ts'),
  '// Generated by npm run build from your NW_SEED. Simulated server files only: no answer list. Do not edit.\n' +
  "import { TerminalData } from './generate';\n" + `export const TDATA: TerminalData = ${JSON.stringify(term.data)};\n`);

// 2. Type-check and build the game.
run('npx tsc --noEmit');
run('npx esbuild src/main.ts --bundle --minify --format=iife --target=es2019 --legal-comments=none --outfile=js/app.js --log-level=warning');

// 3. Build the class server. It contains no secrets: it reads NW_SEED from Script properties.
run('npx esbuild src/server/verify.ts --bundle --format=iife --global-name=BV --target=es2019 --outfile=backend/.verify.js --log-level=warning');
const tpl = fs.readFileSync(P('backend/Code.template.gs'), 'utf8');
const bv = fs.readFileSync(P('backend/.verify.js'), 'utf8');
fs.unlinkSync(P('backend/.verify.js'));
const code = tpl + '\n/* ---- checker, generated from src/server/verify.ts. Do not edit below. ---- */\n' + bv;
fs.writeFileSync(P('backend/Code.gs'), code);

// 4. Safety checks: the seed must never be in any public file.
const app = fs.readFileSync(P('js/app.js'), 'utf8');
if (app.includes(seed) || code.includes(seed)) { console.error('STOP: the secret seed leaked into a public file.'); process.exit(1); }

// 5. Teacher answer key (private). Passcodes match the server: HMAC-SHA256(key = seed, "passcode:" + level).
const ADJ = tpl.match(/const ADJ = \[([\s\S]*?)\];/)[1].match(/'([a-z]+)'/g).map(w => w.slice(1, -1));
const NOUN = tpl.match(/const NOUN = \[([\s\S]*?)\];/)[1].match(/'([a-z]+)'/g).map(w => w.slice(1, -1));
const pass = id => { const b = crypto.createHmac('sha256', seed).update('passcode:' + id).digest(); return `${ADJ[b[0] % 64]}-${NOUN[b[1] % 64]}-${10 + (b[2] % 90)}`; };
if (!process.env.CI) {
  const ids = Array.from({ length: 12 }, (_, i) => 'nw' + (i + 1));
  fs.mkdirSync(P('private'), { recursive: true });
  fs.writeFileSync(P('private/ANSWER-KEY.md'), `# Night Watch answer key for this installation (PRIVATE)

Built from the seed in private/nw-seed.txt. Another school with another seed has different answers.

## Log hunts
| Level | Answer |
| --- | --- |
| 3 Knock Knock | ${g.answers.nw3} |
| 4 The Open Door | ${g.answers.nw4} |
| 7 Count the Guesses | ${g.answers.nw7} |
| 11 Low and Slow | ${g.answers.nw11} |

## Passcodes (each unlocks the next level)
| After level | Passcode |
| --- | --- |
${ids.map((id, i) => `| ${i + 1} | ${pass(id)} |`).join('\n')}

## Control Room
| Level | Answer |
| --- | --- |
| 1 | ${term.answers.op1} |
| 2 | ${term.answers.op2} |
| 3 | ${term.answers.op3} |
| 4 | ${term.answers.op4} |
| 5 | ${term.answers.op5} |
| 6 | ${term.answers.op6} |
| 7 | sudo ufw default deny incoming; sudo ufw allow 80/tcp; sudo ufw allow 443/tcp; sudo ufw allow from 10.0.5.0/24 to any port 22 proto tcp; sudo ufw enable; submit |
| 8 | chmod 600 ~/backup/passwords.txt; submit |
| 9 | ${term.answers.op9} |
| 10 | sudo ufw insert 1 deny from ${term.answers.op10}; submit |

Control Room passwords (each unlocks the next level):
${Array.from({ length: 10 }, (_, i) => `- after level ${i + 1}: ${pass('op' + (i + 1))}`).join('\n')}

## Sample solutions for rule levels
See TEACHER-KIT.md, section "Sample solutions".
`);
}
console.log(`Built js/app.js (${Math.round(app.length / 1024)} KB) and backend/Code.gs. Seed checked: not in any public file.`);
